name: netsim
version: 0.0.0.0
ghc-options: -Wall -fwarn-tabs -fwarn-incomplete-record-updates -fwarn-monomorphism-restriction -fwarn-unused-do-bind
dependencies:
  - base
  - containers
  - brick
  - vty
  - microlens
  - microlens-th
  - microlens-mtl
  - mtl
  - socket
  - bytestring
  - cereal
  - stm

library:
  exposed-modules: 
    - NetSim.Core
    - NetSim.Examples.Calculator.Calculator
    - NetSim.Interpretations.WebSockets
  source-dirs: src

executables:
  poly-server: 
    dependencies:
      - netsim
    ghc-options:
      - -main-is 
      - NetSim.Examples.Calculator.Server
    main: src/NetSim/Examples/Calculator/Server.hs
  poly-client: 
    dependencies:
      - netsim
    ghc-options:
      - -main-is 
      - NetSim.Examples.Calculator.Client
    main: src/NetSim/Examples/Calculator/Client.hs

